// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkB1Sls_MxGQcgQBg7sVEykJmYk0NxQ1A',
    appId: '1:751761510775:android:1eee97ab3617e05b729172',
    messagingSenderId: '751761510775',
    projectId: 'mytravalypractical',
    storageBucket: 'mytravalypractical.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIUkwPQJd2w--aZSTIfsGjUdaYQE9ZSYE',
    appId: '1:751761510775:ios:47de24ffcc104a70729172',
    messagingSenderId: '751761510775',
    projectId: 'mytravalypractical',
    storageBucket: 'mytravalypractical.firebasestorage.app',
    androidClientId: '751761510775-1h84u5d7d6spjr0vm87ovjvd508q9ur9.apps.googleusercontent.com',
    iosClientId: '751761510775-qursj46vpm5pdfg0u172pvsi66m8t7os.apps.googleusercontent.com',
    iosBundleId: 'com.mytravaly.mytravaly',
  );
}
